version: '3.8'

volumes:
  dbdata_mysql_maria:

services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    container_name: americor-app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - app-network

  mysql:
    image: mariadb:10.5.2
    container_name: americor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: americor-test
    volumes:
      - "dbdata_mysql_maria:/var/lib/mysql"
    ports:
      - 127.0.0.1:3503:3306
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
